version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: your-gitlab-url
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://your-gitlab-url:8081';"
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network
networks:
  gitlab-network:
    driver: bridge
